Repository PMM-Dev/moonshot, pull requests merged in 2020-11, with the labels that each got.

#2 System Part Commits that is developed during period from start to 11.12 meeting
  Assets/1.Scenes/Lobby.unity
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/Main.unity.meta
  Assets/2.Scripts/System/DummyMovement.cs
  Assets/2.Scripts/System/LobbyUIManager.cs
  Assets/2.Scripts/System/LobbyUIManager.cs.meta
  Assets/2.Scripts/System/SmoothTargetFollowing.cs
  Assets/2.Scripts/System/main.meta
  Assets/2.Scripts/System/main/MainDataManager.cs
  Assets/2.Scripts/System/main/MainDataManager.cs.meta
  Assets/2.Scripts/System/main/MainEventManager.cs
  Assets/2.Scripts/System/main/MainEventManager.cs.meta
  Assets/2.Scripts/System/main/MainUIManager.cs
  Assets/2.Scripts/System/main/MainUIManager.cs.meta
  Assets/2.Scripts/System/main/SmoothTargetFollowing.cs
  Assets/2.Scripts/System/main/SmoothTargetFollowing.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#7 Enemy Pattern and move
  Assets/0.Files/Images/Enemy/Dummy.meta
  Assets/0.Files/Images/Enemy/Dummy/Martian.png
  Assets/0.Files/Images/Enemy/Dummy/Martian.png.meta
  Assets/0.Files/Images/Enemy/Dummy/slug.png
  Assets/0.Files/Images/Enemy/Dummy/slug.png.meta
  Assets/0.Files/Images/Enemy/Dummy/wolf.png
  Assets/0.Files/Images/Enemy/Dummy/wolf.png.meta
  Assets/2.Scripts/Enemy/EnemyMove.cs
  Assets/2.Scripts/Enemy/ExplosionkPattern.cs
  Assets/2.Scripts/Enemy/ExplosionkPattern.cs.meta
  Assets/2.Scripts/Enemy/MeleeAttackPattern.cs
  Assets/2.Scripts/Enemy/MeleeAttackPattern.cs.meta
  Assets/2.Scripts/Enemy/Patten.cs
  Assets/2.Scripts/Enemy/Pattern.cs
  Assets/2.Scripts/Enemy/Pattern.cs.meta
  Assets/3.Prefabs/Enemy/Martian Dummy.prefab
  Assets/3.Prefabs/Enemy/Martian Dummy.prefab.meta
  Assets/3.Prefabs/Enemy/Rabbit.prefab
  Assets/3.Prefabs/Enemy/Slug Dummy.prefab
  Assets/3.Prefabs/Enemy/Slug Dummy.prefab.meta
  Assets/3.Prefabs/Enemy/Werewolf Dummy.prefab
  Assets/3.Prefabs/Enemy/Werewolf Dummy.prefab.meta
Labels: enhancement

#9 #8 PlayerController의 모든 움직임에서 Rigidbody 제거
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Player/CollisionTrigger.cs
  Assets/2.Scripts/Player/PlayerCollisionTrigger.cs
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerLogic.cs
  Assets/2.Scripts/Player/PlayerSimulation.cs
  Packages/packages-lock.json
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: enhancement

#12 Implement player's slash attack
  Assets/0.Files/Images/Player/Animation/player_parts 1.controller
  Assets/0.Files/Images/Player/Animation/player_slash.anim
  Assets/0.Files/Images/Player/Animation/player_slash.anim.meta
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Player/Define.cs
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerEffect.cs
  Assets/2.Scripts/Player/PlayerEffect.cs.meta
  Assets/2.Scripts/Player/PlayerInput.cs
  Assets/2.Scripts/Player/PlayerLogic.cs
  Assets/2.Scripts/Player/PlayerSimulation.cs
  Assets/3.Prefabs/Player/Player.prefab
  Assets/3.Prefabs/Player/SlashRange.prefab
  Assets/3.Prefabs/Player/SlashRange.prefab.meta
Labels: enhancement

#19 Stick detection, bottom jump
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerInput.cs
  Assets/2.Scripts/Player/PlayerLogic.cs
  Assets/3.Prefabs/Player/Player.prefab
Labels: enhancement

#22 fix : Remove force pausing
  Assets/2.Scripts/Player/PlayerController.cs
Labels: bug

#25 Enemy : feat : Includes a function that damages the player
  Assets/0.Files/Images/Enemy/raser.png
  Assets/0.Files/Images/Enemy/raser.png.meta
  Assets/1.Scenes/Mob&PlayerTest.unity
  Assets/2.Scripts/Enemy/Bullet.cs
  Assets/2.Scripts/Enemy/EnemyMove.cs
  Assets/2.Scripts/Enemy/ExplosionkPattern.cs
  Assets/2.Scripts/Enemy/MeleeAttackPattern.cs
  Assets/2.Scripts/Enemy/Pattern.cs
  Assets/2.Scripts/Enemy/Raser.cs
  Assets/3.Prefabs/Enemy/Bullit.prefab
  Assets/3.Prefabs/Enemy/GumBang.prefab
  Assets/3.Prefabs/Enemy/MasPeople.prefab
  Assets/3.Prefabs/Enemy/Rabbit.prefab
  Assets/3.Prefabs/Enemy/Wolf.prefab
  ProjectSettings/TagManager.asset
Labels: enhancement

#26 Gravity limitation, slash detection for kill enemy
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/SlashRange.cs
  Assets/2.Scripts/Player/SlashRange.cs.meta
  Assets/3.Prefabs/Player/Player.prefab
  Assets/3.Prefabs/Player/SlashRange.prefab
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#28 Complete rebuilding Main Scene
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerInput.cs
  Assets/2.Scripts/System/main/SmoothTargetFollowing.cs
Labels: enhancement

#30 fix : Add rigidbody for slash detection
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/3.Prefabs/Player/SlashRange.prefab
Labels: bug

#32 MapMaker supplement and refactoring
  Assets/1.Scenes/dev-sjmjys954646-Map.unity
  Assets/2.Scripts/Map/BlockCollideDisappear.cs
  Assets/2.Scripts/Map/MapAttribute.cs
  Assets/2.Scripts/Map/MapAttribute.cs.meta
  Assets/2.Scripts/Map/MapMaking.cs
  Assets/3.Prefabs/Map/MapGenerator.prefab
Labels: enhancement

#31 Bonus movement when success to slash enemy
  Assets/0.Files/Data.meta
  Assets/0.Files/Data/PlayerData.asset
  Assets/0.Files/Data/PlayerData.asset.meta
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Enemy/Life.cs
  Assets/2.Scripts/Interface/IDamage.cs
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerData.cs
  Assets/2.Scripts/Player/PlayerData.cs.meta
  Assets/2.Scripts/Player/PlayerLogic.cs
  Assets/2.Scripts/Player/SlashRange.cs
Labels: enhancement

#33 Enemy : Attach Collider
  Assets/2.Scripts/Enemy/EnemyMove.cs
  Assets/2.Scripts/Enemy/Pattern.cs
  Assets/3.Prefabs/Enemy/GumBang.prefab
  Assets/3.Prefabs/Enemy/MasPeople.prefab
  Assets/3.Prefabs/Enemy/Rabbit.prefab
  Assets/3.Prefabs/Enemy/Wolf.prefab
  Packages/packages-lock.json
Labels: enhancement

#38 feat : Arrow for guide slash direction #37
  Assets/0.Files/Images/Player/Arrow.png
  Assets/0.Files/Images/Player/Arrow.png.meta
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/3.Prefabs/Player/Player.prefab
Labels: enhancement

#42 Make MainGameManager as singleton class
  Assets/0.Files/Images/Particle System.meta
  Assets/0.Files/Images/Particle System/dash.png
  Assets/0.Files/Images/Particle System/dash.png.meta
  Assets/2.Scripts/System/DashGhostFx.cs
  Assets/2.Scripts/System/DashGhostFx.cs.meta
  Assets/2.Scripts/System/DashGhostFxPool.cs
  Assets/2.Scripts/System/DashGhostFxPool.cs.meta
  Assets/2.Scripts/System/main/MainEventManager.cs
  Assets/2.Scripts/System/main/MainGameManager.cs
  Assets/2.Scripts/System/main/MainUIManager.cs
  Assets/3.Prefabs/Particle System.meta
  Assets/3.Prefabs/Particle System/Dash Ghost Pool.prefab
  Assets/3.Prefabs/Particle System/Dash Ghost Pool.prefab.meta
  Assets/3.Prefabs/Particle System/Dash Trail Fx.prefab
  Assets/3.Prefabs/Particle System/Dash Trail Fx.prefab.meta
  Assets/3.Prefabs/Particle System/DashGhostPrefab.prefab
  Assets/3.Prefabs/Particle System/DashGhostPrefab.prefab.meta
Labels: enhancement

#45 Add DashGhostEffect and DashTrailParticle
  Assets/2.Scripts/System/DashGhostFx.cs
  Assets/2.Scripts/System/DashGhostFxPool.cs
  Assets/3.Prefabs/Particle System/DashGhostPrefab.prefab
  Packages/packages-lock.json
Labels: enhancement

#51 Make all particle system what is needed now.
  Assets/0.Files/Attacked Material.mat
  Assets/0.Files/Attacked Material.mat.meta
  Assets/0.Files/Images/Particle System/Attacked Animation.png
  Assets/0.Files/Images/Particle System/Attacked Animation.png.meta
  Assets/0.Files/Images/Particle System/Dash Ghost Image.png
  Assets/0.Files/Images/Particle System/Dash Ghost Image.png.meta
  Assets/0.Files/Images/Particle System/Explosion Monster Body 1.png
  Assets/0.Files/Images/Particle System/Explosion Monster Body 1.png.meta
  Assets/0.Files/Images/Particle System/Explosion Monster Body 2.png
  Assets/0.Files/Images/Particle System/Explosion Monster Body 2.png.meta
  Assets/0.Files/Images/Particle System/Explosion Monster Body 3.png
  Assets/0.Files/Images/Particle System/Explosion Monster Body 3.png.meta
  Assets/0.Files/Images/Particle System/Explosion Monster Body 4.png
  Assets/0.Files/Images/Particle System/Explosion Monster Body 4.png.meta
  Assets/0.Files/Images/Particle System/Explosion Monster Body 5.png
  Assets/0.Files/Images/Particle System/Explosion Monster Body 5.png.meta
  Assets/0.Files/Images/Particle System/Smoke Image.png
  Assets/0.Files/Images/Particle System/Smoke Image.png.meta
  Assets/0.Files/Images/Particle System/effect.png
  Assets/0.Files/Images/Particle System/effect.png.meta
  Assets/0.Files/Images/Particle System/wolf dummy.png
  Assets/0.Files/Images/Particle System/wolf dummy.png.meta
  Assets/1.Scenes/dev-kwon770.unity
  Assets/3.Prefabs/Particle System/Attacked Particle.prefab
  Assets/3.Prefabs/Particle System/Attacked Particle.prefab.meta
  Assets/3.Prefabs/Particle System/Enemy Slashed Particle.prefab
  Assets/3.Prefabs/Particle System/Enemy Slashed Particle.prefab.meta
  Assets/3.Prefabs/Particle System/Explosion Monster Particle.prefab
  Assets/3.Prefabs/Particle System/Explosion Monster Particle.prefab.meta
  Assets/3.Prefabs/Particle System/Grab Particle.prefab
  Assets/3.Prefabs/Particle System/Grab Particle.prefab.meta
  Assets/3.Prefabs/Particle System/Jump Particle.prefab
  Assets/3.Prefabs/Particle System/Jump Particle.prefab.meta
  Assets/3.Prefabs/Particle System/Shoot Particle.prefab
  Assets/3.Prefabs/Particle System/Shoot Particle.prefab.meta
  Assets/3.Prefabs/Particle System/Tile Smoke Particle.prefab
  Assets/3.Prefabs/Particle System/Tile Smoke Particle.prefab.meta
Labels: enhancement

#57 fix : prefab break
  Assets/1.Scenes/dev-sjmjys954646-Map.unity
  Assets/2.Scripts/Map/MakePlayerDie.cs
  Assets/2.Scripts/Map/MapSetActive.cs
  Assets/3.Prefabs/Map/Collider.prefab
  Assets/3.Prefabs/Map/Collider.prefab.meta
  Assets/3.Prefabs/Map/MapGenerator.prefab
  Assets/3.Prefabs/Map/Start_Collider.prefab
  Assets/3.Prefabs/Map/Start_Collider.prefab.meta
Labels: bug

#58 fix : Slash bite issue
  Assets/2.Scripts/Player/PlayerController.cs
Labels: bug

#59 Map Particle Apply and remove white sprite
  Assets/0.Files/Data/MapPlayerData.asset
  Assets/1.Scenes/dev-sjmjys954646-Map.unity
  Assets/2.Scripts/Map/BlockCollideDisappear.cs
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_g.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_gr.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_p.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_pi.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_sky.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_skys.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_horizShort_y.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_g.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_gr.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_p.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_pi.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_sky.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_skys.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verLong_y.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_g.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_gr.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_p.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_pi.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_sky.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_skys.prefab
  Assets/3.Prefabs/Map/Block_Prefab/Block_verShort_y.prefab
  Assets/3.Prefabs/Map/Block_Prefab/ConnectorBlock_horiz.prefab
  Assets/3.Prefabs/Map/Block_Prefab/ConnectorBlock_horizMidlong.prefab
  Assets/3.Prefabs/Map/Block_Prefab/ConnectorBlock_ver.prefab
  Assets/3.Prefabs/Map/MapGenerator.prefab
  Assets/3.Prefabs/Map/Particle.meta
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Connect Horiz Long.prefab
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Connect Horiz Long.prefab.meta
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Connect horiz.prefab
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Connect horiz.prefab.meta
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Connect ver.prefab
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Connect ver.prefab.meta
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Ver Long.prefab
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Ver Long.prefab.meta
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Ver Short.prefab
  Assets/3.Prefabs/Map/Particle/Tile Break Particle Ver Short.prefab.meta
  Assets/3.Prefabs/Map/Particle/Tile Break Particle.prefab
  Assets/3.Prefabs/Map/Particle/Tile Break Particle.prefab.meta
Labels: enhancement

#66 fix : Fix Background follows player
  Assets/2.Scripts/Player/BackgroundController.cs
Labels: bug

#67 Add particle for player
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerFX.cs
  Assets/2.Scripts/System/DashGhostFx.cs
  Assets/2.Scripts/System/DashGhostFxPool.cs
  Assets/3.Prefabs/Particle System/DashGhostPrefab.prefab
  Assets/3.Prefabs/Player/Player.prefab
Labels: enhancement

#71 Player die event
  Assets/0.Files/Images/Player/Animation/player_die.anim
  Assets/0.Files/Images/Player/Animation/player_die.anim.meta
  Assets/0.Files/Images/Player/Animation/player_parts 1.controller
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/3.Prefabs/Player/Player.prefab
Labels: enhancement

#72 fix : Copied code issue
  Assets/2.Scripts/Player/PlayerController.cs
Labels: bug

#73 SoundHelper for stereo sound
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/System/main/ElevatorMovement.cs
  Assets/2.Scripts/System/main/MainSoundManager.cs
  Assets/2.Scripts/System/main/SoundHelper.cs
  Assets/2.Scripts/System/main/SoundHelper.cs.meta
  Assets/Resources/Sound.meta
  Assets/Resources/Sound/FX.meta
  Assets/Resources/Sound/FX/Boom.mp3
  Assets/Resources/Sound/FX/Boom.mp3.meta
  Assets/Resources/Sound/FX/ElevatorDoorOpen.mp3
  Assets/Resources/Sound/FX/ElevatorDoorOpen.mp3.meta
  Assets/Resources/Sound/FX/ElevatorRising.mp3
  Assets/Resources/Sound/FX/ElevatorRising.mp3.meta
  Assets/Resources/Sound/FX/ShootLazer.mp3
  Assets/Resources/Sound/FX/ShootLazer.mp3.meta
  Assets/Resources/Sound/FX/Slash.mp3
  Assets/Resources/Sound/FX/Slash.mp3.meta
  Assets/Resources/Sound/FX/WolfAttack.mp3
  Assets/Resources/Sound/FX/WolfAttack.mp3.meta
Labels: enhancement

#74 Play loop sound
  Assets/2.Scripts/System/main/ElevatorMovement.cs
  Assets/2.Scripts/System/main/MainSoundManager.cs
  Assets/2.Scripts/System/main/SoundHelper.cs
Labels: enhancement

#78 fix : Block overflow error
  Assets/0.Files/Images/Player/bg_sky_2.png
  Assets/0.Files/Images/Player/bg_sky_2.png.meta
  Assets/1.Scenes/dev-manabingsu.unity
  Assets/2.Scripts/Enemy/Move/EnemyMove.cs
  Assets/2.Scripts/System/main/MainSoundManager.cs
  Assets/2.Scripts/System/main/SoundHelper.cs
  Assets/3.Prefabs/Player/BackgroundController.prefab
  Assets/Resources/Sound/FX/MainTheme.mp3
  Assets/Resources/Sound/FX/MainTheme.mp3.meta
  Packages/packages-lock.json
Labels: bug

#84 게임 클리어 이벤트 추가 및 클리어 UI 추가
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/System/main/MainEventManager.cs
  Assets/2.Scripts/System/main/MainUIManager.cs
Labels: enhancement

#88 fix : Null exception of EventSystem
  Assets/2.Scripts/Player/PlayerInput.cs
  Packages/packages-lock.json
Labels: bug

#89 fix : Input issue of EventSystem
  Assets/2.Scripts/Player/PlayerInput.cs
Labels: bug

#93 fix : Remove preact of player
  Assets/0.Files/Images/Player/Arrow_2.png
  Assets/0.Files/Images/Player/Arrow_2.png.meta
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/System/main/MainPlayerManager.cs
  Assets/Resources/Player/Player.prefab
  Assets/Resources/Player/Player.prefab.meta
Labels: bug

#96 chore : Wolf Sound & ani
  Assets/0.Files/Images/Enemy/Animation/WolfMeelAttack.anim
  Assets/0.Files/Images/Enemy/Animation/controller/Wolf.controller
  Assets/1.Scenes/enemy-jsuk10-playere&nemy 1.unity
  Assets/2.Scripts/Enemy/Life.cs
  Assets/2.Scripts/Enemy/MeleeAttackPattern.cs
  Assets/2.Scripts/Enemy/Pattern.cs
  Assets/3.Prefabs/Enemy/GumBang.prefab
  Assets/3.Prefabs/Enemy/MasPeople.prefab
  Assets/3.Prefabs/Enemy/Rabbit.prefab
  Assets/3.Prefabs/Enemy/Wolf.prefab
  Packages/packages-lock.json
Labels: bug, enhancement

#100 fix : Jump again issue
  Assets/0.Files/Data/MapPlayerData.asset
  Assets/0.Files/Data/PlayerData.asset
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerData.cs
Labels: bug, enhancement

#105 feat : Change arrow image
  Assets/0.Files/Images/Player/arrow_blank.png
  Assets/0.Files/Images/Player/arrow_blank.png.meta
  Assets/Resources/Player/Player.prefab
Labels: enhancement

#102 Chore : Resetting
  Assets/0.Files/Images/Enemy/Animation/Gumbang_Idle.anim
  Assets/0.Files/Images/Enemy/Animation/MasPeople.anim
  Assets/0.Files/Images/Enemy/Animation/Rabbit.anim
  Assets/0.Files/Images/Enemy/Animation/Wolf.anim
  Assets/0.Files/Images/Enemy/Animation/controller/MasPeople.controller
  Assets/0.Files/Images/Enemy/Animation/controller/Moon.controller
  Assets/0.Files/Images/Enemy/Animation/controller/Rabbit.controller
  Assets/0.Files/Images/Enemy/Animation/controller/Wolf.controller
  Assets/0.Files/Images/Enemy/Animation/controller/gumbang.controller
  Assets/1.Scenes/enemy-jsuk10-playere&nemy 1.unity
  Assets/2.Scripts/Enemy/Boss/BossLife.cs
  Assets/2.Scripts/Enemy/Boss/Pattern/ExhaustPatterns.cs
  Assets/2.Scripts/Enemy/Boss/PatternController.cs
  Assets/2.Scripts/Enemy/Boss/Projectile/Hat.cs
  Assets/2.Scripts/Enemy/Boss/Projectile/Projectile.cs
  Assets/2.Scripts/Enemy/Life.cs
  Assets/2.Scripts/Enemy/Raser.cs
  Assets/3.Prefabs/Enemy/GumBang.prefab
  Assets/3.Prefabs/Enemy/MasPeople.prefab
  Assets/3.Prefabs/Enemy/Moon 1.prefab
  Assets/3.Prefabs/Enemy/Rabbit.prefab
  Assets/3.Prefabs/Enemy/Wolf.prefab
  Packages/packages-lock.json
Labels: enhancement

#107 feat : Zoom action when slashed
  Assets/0.Files/Data/PlayerData.asset
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerData.cs
  Assets/2.Scripts/Player/SlashRange.cs
  Assets/2.Scripts/System/main/CameraFx.cs
Labels: enhancement

#108 chore : apply Boss Prefabs
  Assets/3.Prefabs/Enemy/Moon 1.prefab
Labels: enhancement

#110 chore : Resetting Boss
  Assets/2.Scripts/Enemy/Boss/Pattern/SingPattern.cs
  Assets/3.Prefabs/Enemy/Moon 1.prefab
Labels: documentation

#111 Player default mode
  Assets/Resources/Player/Player.prefab
Labels: enhancement

#113 New intro and BulletTime background
  Assets/0.Files/Images/Player/focus.png
  Assets/0.Files/Images/Player/focus.png.meta
  Assets/0.Files/Images/Player/focus_.png
  Assets/0.Files/Images/Player/focus_.png.meta
  Assets/0.Files/Intro.mp4
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/Player/BulletTimePanel.cs
  Assets/2.Scripts/Player/BulletTimePanel.cs.meta
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/3.Prefabs/Main Canvas.prefab
  Assets/3.Prefabs/Main Canvas.prefab.meta
  Assets/Resources/Player/Player.prefab
Labels: enhancement

#115 Feat : Die event
  Assets/0.Files/Images/Enemy/Animation/Moon/AfterDie.anim
  Assets/0.Files/Images/Enemy/Animation/Moon/AfterDie.anim.meta
  Assets/0.Files/Images/Enemy/Animation/Moon/Exhaust.anim
  Assets/0.Files/Images/Enemy/Animation/Moon/Mad.anim
  Assets/0.Files/Images/Enemy/Animation/Moon/SlashLeft.anim
  Assets/0.Files/Images/Enemy/Animation/Moon/SlashRight.anim
  Assets/0.Files/Images/Enemy/Animation/controller/Moon.controller
  Assets/1.Scenes/enemy-jsuk10-playere&nemy 1.unity
  Assets/2.Scripts/Enemy/Boss/BossLife.cs
  Assets/2.Scripts/Enemy/Boss/Pattern/ExhaustPatterns.cs
  Assets/2.Scripts/Enemy/Boss/Pattern/MadPattern.cs
  Assets/2.Scripts/Enemy/Boss/Projectile/Hat.cs
  Assets/2.Scripts/Enemy/Move/EnemyMove.cs
  Packages/packages-lock.json
Labels: bug, enhancement

#117 Ending BGM, Hot key for test mode
  Assets/2.Scripts/Player/BulletTimePanel.cs
  Assets/2.Scripts/Player/Define.cs
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerInput.cs
  Assets/2.Scripts/Player/PlayerLogic.cs
  Assets/2.Scripts/System/main/MainSoundManager.cs
  Assets/Resources/Player/BulletTime.meta
  Assets/Resources/Player/BulletTime/focus.png
  Assets/Resources/Player/BulletTime/focus.png.meta
  Assets/Resources/Player/BulletTime/focus_test.png
  Assets/Resources/Player/BulletTime/focus_test.png.meta
  Assets/Resources/Sound/FX/Ending.mp3
  Assets/Resources/Sound/FX/Ending.mp3.meta
Labels: enhancement

#116 시스템 개발 완료
  Assets/0.Files/Fonts/dummy.cs
  Assets/0.Files/Fonts/dummy.cs.meta
  Assets/0.Files/Images/Shutdown Icon.png
  Assets/0.Files/Images/Shutdown Icon.png.meta
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/1.Scenes/RestartedMain.unity.meta
  Assets/1.Scenes/dev-kwon770.unity
  Assets/2.Scripts/System/main/MainGameManager.cs
  Assets/2.Scripts/System/main/MainUIManager.cs
  Assets/dummy.cs
  Assets/dummy.cs.meta
  Packages/packages-lock.json
Labels: enhancement

#119 fix : Remove main restart
  Assets/1.Scenes/RestartedMain.unity
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#120 Fix ending bgm issue
  Assets/2.Scripts/System/main/MainSoundManager.cs
Labels: bug

#121 fix : Framerate fix to 60
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/System/main/MainGameManager.cs
Labels: enhancement

#122 fix : Credit speed
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
Labels: enhancement

#124 feat : Fade out for main
  Assets/0.Files/Images/MuteIcon.png
  Assets/0.Files/Images/MuteIcon.png.meta
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/System/Intro.cs
  Assets/2.Scripts/System/main/MainSoundManager.cs
  Assets/2.Scripts/System/main/MainUIManager.cs
Labels: enhancement

#125 fix : Project setting
  ProjectSettings/ProjectSettings.asset
Labels: bug

#128 feat : Elevator resource
  Assets/0.Files/Images/Main.meta
  Assets/0.Files/Images/Main/Elevator_Body.png
  Assets/0.Files/Images/Main/Elevator_Body.png.meta
  Assets/0.Files/Images/Main/Elevator_Left.png
  Assets/0.Files/Images/Main/Elevator_Left.png.meta
  Assets/0.Files/Images/Main/Elevator_Right.png
  Assets/0.Files/Images/Main/Elevator_Right.png.meta
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/System/main/ElevatorMovement.cs
Labels: enhancement

#129 Map : change credit
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/3.Prefabs/Map/MapGenerator.prefab
Labels: enhancement

#133 fix : Main canvas active
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/System/main/MainSoundManager.cs
Labels: bug

#134 fix : Main panel active
  Assets/1.Scenes/RestartedMain.unity
Labels: bug

#135 fix : Start Boss Die Ani
  Assets/2.Scripts/Enemy/Boss/BossLife.cs
  Assets/2.Scripts/Enemy/Boss/Pattern/ExhaustPatterns.cs
  Assets/2.Scripts/Enemy/Boss/PatternController.cs
  Assets/3.Prefabs/Enemy/Moon 1.prefab
Labels: bug

#139 Raycast for check collision
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/2.Scripts/Player/PlayerData.cs
  Assets/Resources/Player/SlashRange.prefab
Labels: bug, enhancement

#141 fix : Slash range alpha
  Assets/Resources/Player/SlashRange.prefab
Labels: bug

#150 Background effect for player die event
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/Player/BulletTimePanel.cs
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/3.Prefabs/Player/BulletTimePanel.prefab
  Assets/3.Prefabs/Player/BulletTimePanel.prefab.meta
Labels: enhancement

#147 fix : issue/146
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/Map/BlockCollideDisappear.cs
  Assets/2.Scripts/Map/MapSetActive.cs
  Assets/2.Scripts/Map/StartBlock.cs
  Assets/3.Prefabs/Map/MapGenerator.prefab
Labels: enhancement

#152 Issue/145
  Assets/0.Files/Images/Tutorial.png
  Assets/0.Files/Images/Tutorial.png.meta
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/System/Intro.cs
  Assets/2.Scripts/System/main/MainUIManager.cs
Labels: enhancement

#154 feat : Soundmanager onclick method
  Assets/2.Scripts/System/main/MainSoundManager.cs
Labels: enhancement

#156 Fix Issue/143
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/System/main/MainSoundManager.cs
  Assets/2.Scripts/System/main/MainUIManager.cs
  Packages/packages-lock.json
Labels: enhancement

#158 fix: Fix slowtime bug
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/1.Scenes/dev-kwon770.unity
  Assets/2.Scripts/Player/PlayerController.cs
Labels: bug, enhancement

#159 feat : Release version 1.0.1
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#160 feat : Hot key for quick start #145
  Assets/1.Scenes/Main.unity
  Assets/2.Scripts/System/StartHotKey.cs
  Assets/2.Scripts/System/StartHotKey.cs.meta
Labels: enhancement

#162 Bullet time background issue and grab particle color
  Assets/2.Scripts/Player/PlayerController.cs
  Assets/3.Prefabs/Particle System/Grab Particle 1.prefab
  Assets/Resources/Player/Player.prefab
Labels: bug

#163 Add 1600x900 resolution
  Assets/1.Scenes/Main.unity
  Assets/1.Scenes/RestartedMain.unity
  Assets/2.Scripts/System/main/MainUIManager.cs
Labels: enhancement
